name: image_downloader_web
description: A Flutter plugin for downloading images from URL to user's device. This plugin only works for Flutter web.
version: 2.0.1
repository: https://github.com/hrvojecukman/image_downloader_web

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1



flutter:
  plugin:
    platforms:
      web:

    funding:
      - https://www.buymeacoffee.com/hrvojecukman